/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCardModal: typeof import('./src/components/AddCardModal.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    WebsiteCard: typeof import('./src/components/WebsiteCard.vue')['default']
  }
}
