services:
  frontend:
    image: herio66/nav-panel-frontend:latest
    container_name: nav-panel-frontend
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - nav-panel-network
    environment:
      - NODE_ENV=production

  backend:
    image: herio66/nav-panel-backend:latest
    container_name: nav-panel-backend
    restart: unless-stopped
    expose:
      - '8080'
    volumes:
      - nav-panel-data:/app/data
    networks:
      - nav-panel-network
    environment:
      - GIN_MODE=release
      - CGO_ENABLED=1
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '-O',
          '/dev/null',
          'http://localhost:8080/api/ping',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nav-panel-data:
    driver: local

networks:
  nav-panel-network:
    driver: bridge
